/**
 * Executive Summary Service — Issue #547
 *
 * Auto-generates executive summaries for CCC reports from defect data.
 * Supports manual override via PUT.
 */

import type { PrismaClient, Report } from '@prisma/client';

// ──────────────────────────────────────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────────────────────────────────────

export interface ExecutiveSummary {
  keyFindings: string[];
  breachedClauses: { code: string; title: string; count: number }[];
  recommendation: string;
  estimatedCost?: number;
  isAutoGenerated: boolean;
}

export class ReportNotFoundError extends Error {
  constructor(id: string) {
    super(`Report not found: ${id}`);
    this.name = 'ReportNotFoundError';
  }
}

export class InvalidReportTypeError extends Error {
  constructor(type: string) {
    super(`Executive summary is only available for CCC_GAP reports, got: ${type}`);
    this.name = 'InvalidReportTypeError';
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Service
// ──────────────────────────────────────────────────────────────────────────────

export class ExecutiveSummaryService {
  constructor(private prisma: PrismaClient) {}

  /**
   * Get the current executive summary for a report.
   */
  async get(reportId: string): Promise<ExecutiveSummary | null> {
    const report = await this.findReport(reportId);
    return (report.executiveSummary as unknown as ExecutiveSummary) ?? null;
  }

  /**
   * Auto-generate executive summary from defect data.
   */
  async generate(reportId: string): Promise<ExecutiveSummary> {
    const report = await this.findReport(reportId);

    if (report.type !== 'CCC_GAP') {
      throw new InvalidReportTypeError(report.type);
    }

    // Get defects for the linked inspection
    const inspectionId = report.siteInspectionId;
    if (!inspectionId) {
      // No inspection linked — return empty summary
      const empty: ExecutiveSummary = {
        keyFindings: ['No inspection data available.'],
        breachedClauses: [],
        recommendation: 'Link a site inspection to generate findings.',
        isAutoGenerated: true,
      };
      await this.save(reportId, empty);
      return empty;
    }

    const defects = await this.prisma.defect.findMany({
      where: { inspectionId },
      include: { linkedClause: true },
    });

    const summary = this.buildSummary(defects);

    await this.save(reportId, summary);
    return summary;
  }

  /**
   * Manually update the executive summary (override auto-generated).
   */
  async update(reportId: string, data: Partial<Omit<ExecutiveSummary, 'isAutoGenerated'>>): Promise<ExecutiveSummary> {
    const report = await this.findReport(reportId);

    if (report.type !== 'CCC_GAP') {
      throw new InvalidReportTypeError(report.type);
    }

    const existing = (report.executiveSummary as unknown as ExecutiveSummary) ?? {
      keyFindings: [],
      breachedClauses: [],
      recommendation: '',
      isAutoGenerated: false,
    };

    const updated: ExecutiveSummary = {
      ...existing,
      ...data,
      isAutoGenerated: false,
    };

    await this.save(reportId, updated);
    return updated;
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Private
  // ────────────────────────────────────────────────────────────────────────────

  private async findReport(reportId: string): Promise<Report> {
    const report = await this.prisma.report.findUnique({
      where: { id: reportId },
    });
    if (!report) throw new ReportNotFoundError(reportId);
    return report;
  }

  private async save(reportId: string, summary: ExecutiveSummary): Promise<void> {
    await this.prisma.report.update({
      where: { id: reportId },
      data: { executiveSummary: summary as object },
    });
  }

  private buildSummary(defects: Array<{ description: string; priority: string; location: string; linkedClause?: { code: string; title: string } | null }>): ExecutiveSummary {
    if (defects.length === 0) {
      return {
        keyFindings: ['No defects identified during inspection.'],
        breachedClauses: [],
        recommendation: 'No remedial works required. Property may proceed with CCC application.',
        isAutoGenerated: true,
      };
    }

    // Key findings — group by location
    const byLocation = new Map<string, typeof defects>();
    for (const d of defects) {
      const loc = d.location || 'General';
      if (!byLocation.has(loc)) byLocation.set(loc, []);
      byLocation.get(loc)!.push(d);
    }

    const keyFindings: string[] = [
      `${defects.length} defect(s) identified requiring remediation`,
    ];

    for (const [location, locationDefects] of byLocation) {
      const descriptions = locationDefects.slice(0, 2).map((d) => d.description);
      keyFindings.push(`${location}: ${descriptions.join('; ')}`);
    }

    // Breached clauses — unique NZBC clauses
    const clauseMap = new Map<string, { code: string; title: string; count: number }>();
    for (const d of defects) {
      if (d.linkedClause) {
        const key = d.linkedClause.code;
        const existing = clauseMap.get(key);
        if (existing) {
          existing.count++;
        } else {
          clauseMap.set(key, { code: key, title: d.linkedClause.title, count: 1 });
        }
      }
    }
    const breachedClauses = Array.from(clauseMap.values()).sort((a, b) => a.code.localeCompare(b.code));

    // Recommendation based on priority
    const hasHigh = defects.some((d) => d.priority === 'HIGH' || d.priority === 'CRITICAL');
    const recommendation = hasHigh
      ? 'Remedial works required before CCC application can proceed.'
      : 'Minor remedial works recommended. Property may proceed with CCC application subject to noted items being addressed.';

    return {
      keyFindings,
      breachedClauses,
      recommendation,
      isAutoGenerated: true,
    };
  }
}
