/**
 * Executive Summary Tests — Issue #547
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ExecutiveSummaryService, ReportNotFoundError, InvalidReportTypeError } from '../services/executive-summary.js';

// ──────────────────────────────────────────────────────────────────────────────
// Mock Prisma
// ──────────────────────────────────────────────────────────────────────────────

function makeMockPrisma() {
  return {
    report: {
      findUnique: vi.fn(),
      update: vi.fn(),
    },
    defect: {
      findMany: vi.fn(),
    },
  } as never;
}

function makeCCCReport(overrides = {}) {
  return {
    id: 'report-1',
    type: 'CCC_GAP',
    siteInspectionId: 'insp-1',
    executiveSummary: null,
    ...overrides,
  };
}

function makeDefect(overrides = {}) {
  return {
    id: 'defect-1',
    description: 'Flashing issue at window',
    location: 'Bathroom',
    priority: 'HIGH',
    linkedClause: { code: 'E2', title: 'External Moisture' },
    ...overrides,
  };
}

// ──────────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────────

describe('ExecutiveSummaryService', () => {
  let prisma: ReturnType<typeof makeMockPrisma>;
  let service: ExecutiveSummaryService;

  beforeEach(() => {
    prisma = makeMockPrisma();
    service = new ExecutiveSummaryService(prisma);
  });

  describe('get', () => {
    it('returns null when no executive summary exists', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport());
      const result = await service.get('report-1');
      expect(result).toBeNull();
    });

    it('returns existing executive summary', async () => {
      const summary = { keyFindings: ['Test'], breachedClauses: [], recommendation: 'OK', isAutoGenerated: true };
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport({ executiveSummary: summary }));
      const result = await service.get('report-1');
      expect(result).toEqual(summary);
    });

    it('throws ReportNotFoundError for unknown report', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(null);
      await expect(service.get('bad-id')).rejects.toThrow(ReportNotFoundError);
    });
  });

  describe('generate', () => {
    it('generates summary from defect data', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport());
      (prisma as any).defect.findMany.mockResolvedValue([
        makeDefect(),
        makeDefect({ id: 'defect-2', description: 'Cracked tiles', location: 'Kitchen', linkedClause: { code: 'B2', title: 'Durability' }, priority: 'MEDIUM' }),
      ]);
      (prisma as any).report.update.mockResolvedValue({});

      const result = await service.generate('report-1');

      expect(result.isAutoGenerated).toBe(true);
      expect(result.keyFindings[0]).toContain('2 defect(s)');
      expect(result.breachedClauses).toHaveLength(2);
      expect(result.breachedClauses.map((c: any) => c.code).sort()).toEqual(['B2', 'E2']);
      expect(result.recommendation).toContain('Remedial works required');
    });

    it('generates empty summary when no defects', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport());
      (prisma as any).defect.findMany.mockResolvedValue([]);
      (prisma as any).report.update.mockResolvedValue({});

      const result = await service.generate('report-1');

      expect(result.keyFindings[0]).toContain('No defects');
      expect(result.breachedClauses).toHaveLength(0);
    });

    it('generates empty summary when no inspection linked', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport({ siteInspectionId: null }));
      (prisma as any).report.update.mockResolvedValue({});

      const result = await service.generate('report-1');

      expect(result.keyFindings[0]).toContain('No inspection data');
    });

    it('throws InvalidReportTypeError for non-CCC reports', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport({ type: 'COA' }));
      await expect(service.generate('report-1')).rejects.toThrow(InvalidReportTypeError);
    });

    it('extracts unique breached clauses', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport());
      (prisma as any).defect.findMany.mockResolvedValue([
        makeDefect({ id: 'd1', linkedClause: { code: 'E2', title: 'External Moisture' } }),
        makeDefect({ id: 'd2', linkedClause: { code: 'E2', title: 'External Moisture' } }),
        makeDefect({ id: 'd3', linkedClause: { code: 'B1', title: 'Structure' } }),
      ]);
      (prisma as any).report.update.mockResolvedValue({});

      const result = await service.generate('report-1');

      expect(result.breachedClauses).toHaveLength(2);
      const e2 = result.breachedClauses.find((c) => c.code === 'E2');
      expect(e2?.count).toBe(2);
    });

    it('groups findings by location', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport());
      (prisma as any).defect.findMany.mockResolvedValue([
        makeDefect({ id: 'd1', location: 'Bathroom', description: 'Leak' }),
        makeDefect({ id: 'd2', location: 'Bathroom', description: 'Mould' }),
        makeDefect({ id: 'd3', location: 'Kitchen', description: 'Cracks' }),
      ]);
      (prisma as any).report.update.mockResolvedValue({});

      const result = await service.generate('report-1');

      // Should have findings grouped by location
      const bathroomFinding = result.keyFindings.find((f) => f.includes('Bathroom'));
      expect(bathroomFinding).toBeDefined();
      expect(bathroomFinding).toContain('Leak');
    });

    it('saves generated summary to database', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport());
      (prisma as any).defect.findMany.mockResolvedValue([makeDefect()]);
      (prisma as any).report.update.mockResolvedValue({});

      await service.generate('report-1');

      expect((prisma as any).report.update).toHaveBeenCalledWith({
        where: { id: 'report-1' },
        data: { executiveSummary: expect.objectContaining({ isAutoGenerated: true }) },
      });
    });
  });

  describe('update', () => {
    it('updates executive summary with manual data', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport({
        executiveSummary: { keyFindings: ['Old'], breachedClauses: [], recommendation: 'Old', isAutoGenerated: true },
      }));
      (prisma as any).report.update.mockResolvedValue({});

      const result = await service.update('report-1', {
        recommendation: 'Updated recommendation',
      });

      expect(result.recommendation).toBe('Updated recommendation');
      expect(result.isAutoGenerated).toBe(false);
      expect(result.keyFindings).toEqual(['Old']); // preserved
    });

    it('throws InvalidReportTypeError for non-CCC reports', async () => {
      (prisma as any).report.findUnique.mockResolvedValue(makeCCCReport({ type: 'PPI' }));
      await expect(service.update('report-1', { recommendation: 'test' })).rejects.toThrow(InvalidReportTypeError);
    });
  });
});
